# Generated by Django 3.0.8 on 2020-11-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201112_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'sedentary'), ('moderately_active', 'moderately active'), ('very_active', 'very active')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_goals',
            field=models.CharField(choices=[('lose_weight', 'lose weight'), ('maintain_weight', 'maintain weight'), ('gain_weight', 'gain weight')], default=0, max_length=20),
        ),
    ]
