# Generated by Django 3.0.8 on 2020-11-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201112_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_aerobic_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_dairy_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_fruit_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_grains_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_muscle_strengthening_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_protein_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_vegetables_target',
            field=models.IntegerField(default=0),
        ),
    ]
