# Generated by Django 3.0.8 on 2020-11-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201113_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_goals',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Maintain Weight', 'Maintain Weight'), ('Gain Weight', 'Gain Weight')], default=0, max_length=20),
        ),
    ]
