# Generated by Django 3.0.8 on 2020-11-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201113_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='custom_aerobic_target',
            field=models.IntegerField(default='blank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_dairy_target',
            field=models.IntegerField(default='blank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_fruit_target',
            field=models.IntegerField(default='blank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_grains_target',
            field=models.IntegerField(default='blank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_muscle_strengthening_target',
            field=models.IntegerField(default='blank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_protein_target',
            field=models.IntegerField(default='blank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_vegetables_target',
            field=models.IntegerField(default='blank'),
        ),
    ]
