# Generated by Django 3.0.8 on 2020-11-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201113_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focus_area_1',
            field=models.CharField(choices=[('Eat enough grains', 'Eat enough grains'), ('Eat enough protein', 'Eat enough protein'), ('Eat enough dairy', 'Eat enough dairy'), ('Eat enough vegetables', 'Eat enough vegetables'), ('Limit grains intake', 'Limit grains intake'), ('Limit protein intake', 'Limit protein intake'), ('Limit dairy intake', 'Limit dairy intake'), ('Limit vegetables intake', 'Limit vegetables intake'), ('Limit fruit intake', 'Limit fruit intake'), ('Reach aerobic exercise targets', 'Reach aerobic exercise targets'), ('Reach muscle strengthening targets', 'Reach muscle strengthening targets')], default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='focus_area_2',
            field=models.CharField(choices=[('Eat enough grains', 'Eat enough grains'), ('Eat enough protein', 'Eat enough protein'), ('Eat enough dairy', 'Eat enough dairy'), ('Eat enough vegetables', 'Eat enough vegetables'), ('Limit grains intake', 'Limit grains intake'), ('Limit protein intake', 'Limit protein intake'), ('Limit dairy intake', 'Limit dairy intake'), ('Limit vegetables intake', 'Limit vegetables intake'), ('Limit fruit intake', 'Limit fruit intake'), ('Reach aerobic exercise targets', 'Reach aerobic exercise targets'), ('Reach muscle strengthening targets', 'Reach muscle strengthening targets')], default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='focus_area_3',
            field=models.CharField(choices=[('Eat enough grains', 'Eat enough grains'), ('Eat enough protein', 'Eat enough protein'), ('Eat enough dairy', 'Eat enough dairy'), ('Eat enough vegetables', 'Eat enough vegetables'), ('Limit grains intake', 'Limit grains intake'), ('Limit protein intake', 'Limit protein intake'), ('Limit dairy intake', 'Limit dairy intake'), ('Limit vegetables intake', 'Limit vegetables intake'), ('Limit fruit intake', 'Limit fruit intake'), ('Reach aerobic exercise targets', 'Reach aerobic exercise targets'), ('Reach muscle strengthening targets', 'Reach muscle strengthening targets')], default=0, max_length=40),
        ),
    ]
