# Generated by Django 3.0.8 on 2020-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201115_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_level',
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_aerobic_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_dairy_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_fruit_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_grains_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_muscle_strengthening_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_protein_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_vegetables_target',
            field=models.IntegerField(default=0),
        ),
    ]
